### PR TITLE
Pyspark implementation

### PR DESCRIPTION
**Pull request by azachar**
Hello @fritshermans,

In order to provide a parallel processing I implemented your library in pyspark. 

At this moment, the notebook and documentation is not done, I have just functional tests + code. 

I believe that the pandas vs pyspark are codewise so different, that it would make sense to keep 2 repositories instead of one. 

I happy to hear your opinion here. 

PS: PySpark reached your accuracy with only 100 hash functions instead of 1000. ;) 

I look forward for your message!

Cheers,
Andrej

### CODE REVIEW

**Comment by fritshermans** [comment]
Hi @azachar, I'm aware of the PySpark implementation of minhashing. The reason I created PyMinHash is that there was no minhash implementation in Python with approximate similarity joining yet (to my knowledge). I don't see the use of a Python package that only calls standard PySpark library functions (NGram, CountVectorizer, VectorAssembler etc) but you're obviously free to create such package if you deem it is useful.

**Comment by azachar** [comment]
Thank you for your quick reply and your opinion.

My main motivation is to port deduplipy into pyspark and this was a dependency, so I tried to "refactor" it and keep the logic as the same as possible, only what I changed was the underlaying stack from pandas to pyspark. 

But you are right, it wont' make sense to maintain a special library just for a special case of deduplipy.

Would you be interested in a pyspark implementation of deduplipy? 

Have a nice evening, 
Andrej

**Comment by fritshermans** [comment]
a paspark implementation of deduplipy is almost finished, we'll open source it in a couple of weeks

**Comment by azachar** [comment]
Cool! I'm happy to join the effort :)

**Pull request closed without merging**
